### PR TITLE
use totalSupply instead of total_supply

### PR DESCRIPTION
**Pull request by u2**
The state variables should be camelCase.

### CODE REVIEW

**Comment by CJentzsch** [comment]
In principal I agree, but I use the standardToken: https://github.com/ConsenSys/Tokens/blob/master/Token_Contracts/contracts/Standard_Token.sol
So please make a PR there, or in the discussion here: https://github.com/ethereum/wiki/wiki/Standardized_Contract_APIs

**Comment by u2** [comment]
ok.

**Comment by CJentzsch** [comment]
soory, this is a better link: https://github.com/ethereum/EIPs/issues/20#issuecomment-176463861

**Comment by u2** [comment]
Thank you. :)

**Comment by CJentzsch** [comment]
In the standard there is already a function called `totalSupply()` , but the name of the variable should be different. I think the best solution is to use `totalSupply` as name of the variable, and make it public. Thereby this function gets created. So I would suggest a PR to https://github.com/ConsenSys/Tokens/blob/master/Token_Contracts/contracts/Standard_Token.sol

**Comment by simondlr** [comment]
Thanks for this! :clap:

**Comment by u2** [comment]
@CJentzsch  so can we reopen this PR?

**Comment by simondlr** [comment]
Just a note. Before pulling new token code in. We are debating in ERC 20 about some of the events. Would love comments on that and for it to be fixed, before recommending pulling in new code. :)

**Pull request closed without merging**
